# Site
name: "Alisa & Eric's Space"
title: "Alisa & Eric's Space"
description: "Welcome to Alisa & Eric's Space! We look forward to sharing our memories with you here."
logo: 'assets/images/love.png'
favicon: 'assets/images/love.png'
baseurl: ''
disqus: 'website'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zmj:
    name: zmj
    display_name: alisa zmj ğŸ’¤
    avatar: 'assets/images/zmj.jpeg'
    description: "å°å™œå™œğŸ·ï½œæ»‘é›ªä¸€çº§çˆ±å¥½è€…ğŸ¿ï½œå½“åœ°å°æœ‰åæ°”çš„ç¾å¥³ğŸ‘§ï½œæ¯å¤©éƒ½å¾ˆçƒ¦ä¸“å®¶ğŸ˜¡ï½œåºŸè¯è¾“å‡ºæœºå™¨ğŸ¤–ï¸ï½œè¿ªå£«å°¼åœ¨é€ƒå…¬ä¸»ğŸ‘¸ï½œçŸ¥åç™½æ—¥åšæ¢¦ç ”ç©¶ä¸“å®¶ğŸ’¤ï½œå¦„æƒ³ä¸€å¤œæš´å¯Œçš„å°åºŸç‰©ğŸ’°ï½œxxçš„è·Ÿå±è™«ğŸ›"
  xx:
    name: xx
    display_name: eric xx ğŸŒŸ
    avatar: 'assets/images/xx.jpg'
    description: "å°å™œå™œçš„é¥²å…»å‘˜ğŸ‘¨ï½œæ»‘é›ªä¸€çº§çˆ±å¥½è€…çš„æ‹†å°ä¸“å®¶ğŸ¿ï½œè½¦æŠ€äº†å¾—çš„å¸æœºğŸš—ï½œç†è®ºå‹æ‘„å½±é€‰æ‰‹ğŸ“·ï½œé€šå¤©è¾¹è·¯ğŸ®ï½œä¸æƒ³å†™ä»£ç çš„ç¨‹åºå‘˜ğŸ’»ï½œå°åºŸç‰©çš„ä¸“å±ä¿é•–ğŸ¤µ"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
